apiVersion: apps/v1
kind: Deployment
metadata:
  name: nino-mlops
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nino-mlops
  template:
    metadata:
      labels:
        app: nino-mlops
    spec:
      containers:
      - name: nino-mlops
        image: us-east1-docker.pkg.dev/melvinai-437118/nino-mlops/hotel-reservation-srv:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: hotel-bookings-filter-service
spec:
  type: LoadBalancer
  selector:
    app: nino-mlops
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080